### ISSUE TITLE
Implement product editing

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-explorer#125]
### What

```[tasklist]
### Tasks
- [ ] Implement basic details editing 
- [ ] Implement product name
- [ ] Implement brand
- [ ] Implement quantity 
- [ ] Implement tag fields editing (categories, labels, origins, stores, traceability codes, countries…)
- [ ] Implement ingredients editing
- [ ] Implement packaging editing
- [ ] Implement producer website editing
- [ ] Implement Folksonomy Engine editing
- [ ] https://github.com/openfoodfacts/openfoodfacts-explorer/issues/114
- [ ] Implement a photo manager
- [ ] Add support for Price edition
```

**Comment by teolemon** [comment]
- [ ] Allow answering the Robotoff questions
![Image](https://github.com/user-attachments/assets/8630dccb-e933-4d00-8ca5-6c55d30dd53a)
- [ ] Allow logging to Open Prices with your main Open Food Facts account (allowing logging with a different account is an idea that should be kept, for people willing to have maximum privacy with an account with their name)
![Image](https://github.com/user-attachments/assets/2d80f3ba-5a9b-4645-bef2-6b3eaa56e559)

**Comment by Sharma-Ji-21** [comment]
@teolemon i would like to work on this issue, could u pls assign this to me

**Comment by KarruHarin** [comment]
@teolemon I tried to clone the repo to set up dev environment , i was able to set it up but was unable to move on to individual product page , as it have its Base_url in .env file of the project .Can I pls get guidence on how to completely set it up ?

**Comment by VaiTon** [comment]
@JiyaGupta-cs sure you can, but please create a PR for a specific bullet point. It would be better to first ask about a specific bullet point so that I can create an issue about it.

@Sharma-Ji-21 same thing. This is an "Epic". It won't be assigned to anyone. It's just to track the missing features. Please ask for a specific bullet point and I can assign you.

@KarruHarin please message me on Slack.

**Comment by Abbas-Askari** [comment]
@VaiTon Can I work on `Implement basic details editing`, I'll add the form feilds in the  `http://localhost:5173/products/[barcode]/edit` page and connect it to the api.
